### ISSUE TITLE
breakaway::betta for repeated measures

### ISSUE THREAD

**Issue by Nick243** [adw96/breakaway#11]
Hi Amy,

It is great to see the continued development the breakaway package!   

The vignettes are extremely helpful and informative.  Extending breakaway to better sync with phyloseq and a post/tutorial about when microbial diversity estimation is and isn't possible (i.e. given issues with calling rare ASV/OTUs) would be very informative (saw your recent post on the dada2 repo).

I write to ask if breakaway::betta can be used (or extended) to account for correlated sampling such as that arising from a two arm longitudinal experimental design?  We have several ongoing studies where we have an interest in modeling the trajectory of diversity indices/estimators over time and ideally would like to account for the inexhaustive sampling.  Our inferences are largely focused on the fixed effects.

Thank you in advance for any thoughts.

**Comment by adw96** [comment]
It absolutely can! The only change to the source code would be in the line

 W <- diag(1/(ssq_u + ses_effective^2))

to add in the additional covariance matrix parameters, which is very easy for me to do once I know the exact design.
(W is the covariance matrix, which is what changes when you have correlated samples)

I think the easiest way to proceed is if we together develop a syntax that you would like betta to use. My preference would be to copy the formatting of whatever model you would use if you were not going to account for inexhaustive sampling (like nlme, where the response is raw alpha diversity scores). How does that sound? Since there are so many possible designs, I think it would be impractical for me to implement them individually, e.g. betta_longitudinal, betta_crossed, betta_splitplot, etc., hence why taking a standard format would probably be best. 

So that I can get you what you need as quickly as possible, could you post the syntax that you would use if you weren't using betta, but instead, another mixed model approach (one that doesn't account for exhaustive sampling)? What are you currently using? nlme?

If you could you give me a small, reproducible example of data and syntax that you're using, I can extend betta to take in that syntax and introduce the additional covariance parameters you need.

I have been meaning to do this for years, but no one has ever pushed me on it -- I'm hoping now this will finally happen!

**Comment by Nick243** [comment]
Thanks so much for your help!  I have attempted to provide some reproducible code below to: 1.) simulate some data that is reasonably-well in line with what we are seeing in our experiments and 2.) the syntax we are using (here just a random intercept and slope model with linear fixed effect for time). 

library(nlme); packageVersion("nlme")                    #version: 3.1.131
library(lme4); packageVersion("lme4")                    #version: 1.1.13
library(simstudy); packageVersion("simstudy")       #version: 0.1.8

set.seed(321)
tdef <- defData(varname = "treatment", dist = "binary", formula = 0.5)
tdef <- defData(tdef, varname = "shannon_t0", dist = "normal", formula = 3.5, variance = .5)
tdef <- defData(tdef, varname = "shannon_t1", dist = "normal", formula = "shannon_t0 + .25 * treatment", variance = .25)
tdef <- defData(tdef, varname = "shannon_t2", dist = "normal", formula = "shannon_t0 + .5 * treatment", variance = .25)
tdef <- defData(tdef, varname = "shannon_t3", dist = "normal", formula = "shannon_t0 + .75 * treatment", variance = .25)
tdef <- defData(tdef, varname = "shannon_t4", dist = "normal", formula = "shannon_t0 + 1 * treatment", variance = .25)
mydata <- genData(20, tdef)

mydata_long <- addPeriods(mydata, nPeriods = 5, idvars = "id", timevars = c("shannon_t0", "shannon_t1", "shannon_t2", "shannon_t3", "shannon_t4"), timevarName = "shannon")

mydata_long$id <- as.factor(mydata_long$id)
mydata_long$time <- mydata_long$period

summary(lme4::lmer(shannon ~ time:treatment + (1 + time|id),data = mydata_long))
summary(nlme::lme(shannon ~ time:treatment, random= ~ 1 + time|id, data = mydata_long))

**Comment by adw96** [comment]
Wonderful -- I can definitely work with this. I will try to do this ASAP -- Friday at earliest, end of the month at latest.

**Comment by adw96** [comment]
I know this is late now, but it's still on my TODO list. I haven't forgotten!

**Comment by adw96** [comment]
Quick update: trying to get a reasonable inference procedure in this setting is pretty difficult. The hierarchical variance structure (estimated variance in diversity estimate + environmental noise + patient specific random effects) is really challenging to estimate without a bunch of different penalties, I'm finding. A naive implementation has Type 1 error rates of >80% when they should be 5%. I'm going to consult with some longitudinal data analysis experts and get back to you!

**Comment by Nick243** [comment]
Hi Amy,

Thanks so much for the update and for following up on this. It is much appreciated!

**Comment by adw96** [comment]
You're very welcome. I'm currently reading about using EM to stabilise it. I tried this back in the day for betta(), but optim was much faster. Back to the drawing board!

**Comment by Nick243** [comment]
Thanks so much for your thoughts on the sampling error versus longitudinal data structure. This is very helpful.  I look forward to any updates and will follow the updates.  I will go ahead and close this for now.  

Thanks for sending the links to the package!  I look forward to checking these out.
