### ISSUE TITLE
Breakaway fails on frequency table

### ISSUE THREAD

**Issue by rprops** [adw96/breakaway#2]
Breakaway seems to fail on some of my samples which have less than 6 non-contiguous frequencies (with force=TRUE). I've included the frequency table in attachment. There is no warning/error message.
[temp.txt](https://github.com/adw96/breakaway/files/615068/temp.txt)

Code that I used
```R
rich <- breakaway::breakaway(temp, print = FALSE, plot = FALSE, answers = TRUE, force=TRUE)
```

**Comment by adw96** [comment]
Hi! Thanks for using breakaway. The force argument is actually not for this issue: it's for concatenation at the other end of the data (e.g. listing all frequency counts between 27 and above under f_27; Fisher's butterfly dataset did this; sometimes ecologists do this too). 

The behavior you describe is deliberate, in fact. breakaway fits relatively highly parametrized models, which is in many ways why does so well compared to other methods. However, to do so successfully it needs more data, as HTS data tends to have. Currently the behaviour is to truncate at the first zero frequency count, which in your dataset is f_5. So breakaway is trying to fit 3+ parameter models to 3 data points (#contiguous frequencies minus one; look at the paper if it's not clear why you need contiguous frequencies). Obviously this is a terrible idea, hence why I stop the code there.

One idea I have been thinking about for years but that has never really come up in practice is that I could have breakaway use all contiguous frequency counts, even after the first missing one. John (Bunge, my collaborator on the methods paper) thinks (or thought, 3 years ago) imputation is better; I disagree. I've never seen a dataset where you had non sparse data after the first missing frequency; yours is the first. So maybe I'll add this in now that I have a use case -- though I reserve the right to revert it if misused/if imputation turns out to be better :)

Here's what I'm going to do
- improve the documentation for force to make its function clearer
- make breakaway produce an error when this happens (you're right, it shouldn't be invisible)
- include all contiguous frequencies, not just the first few. 
I'm afk this week but will be back on dec 5th. I'll do this then and close the issue then. 

Here's what I recommend to you:
- This dataset is actually kind of small compared to breakaways ideal case (e.g. Apples or Epstein). This structure may be better suited to the objective bayes class of estimators. So in the meantime, I'd run 

breakaway::objective_bayes_negbin(temp) ## or something like that; sorry, I'm not at my computer right now 

to get your estimates. In 2 weeks, if you prefer the updated breakaway estimate, you can go with that. I doubt they'll be too different. 

Thanks for your interest and let me know if that's not a satisfactory answer.

Cheers,

Amy
(Sent from my phone, please excuse brevity)

**Comment by adw96** [comment]
Thanks for your patience with me. I've done all 3 things that I promised. The option to include all contiguous frequencies is "useAll,"  which defaults to FALSE (i.e. use only contiguous frequencies up until the first break). 

Unfortunately I have some bad news, which is that breakaway doesn't converge for your dataset even after permitting it to use the additional frequency ratios. Honestly, it's because the data isn't big enough. You have more than 4 x as many OTUs observed once than twice, and combining that with one species observed 7, 8, 9, 10 times and none observed 5 times makes the data you have pretty uninformative for the problem that we're trying to solve. Species richness estimation is a boundary value problem, so quite unstable even in good situations. I'm going to recommend that for species richness comparisons you omit this sample. Unfortunately there's just not enough information for a reasonable estimate. Alternatively, if you are going to use betta for comparisons, you could give it the estimate 277 (the sample richness) or 705 (the Chao lower bound), and use a standard error of 1e8. This is effectively the same as omitting it, but a little more transparent because you're saying that we have no precision in the estimate. 

BTW I played around with the negative binomial objective bayes estimator and you can't get a reasonable estimate out of it either (check out that trace plot!).

Thanks for logging your issue and feel free to reopen it if this didn't address your concerns :)

Amy
