### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by sminot** [adw96/breakaway#57]
It would be nice to have a link to the documentation for `breakaway` from the main GitHub Readme page. If it's there and I missed it, my apologies.

**Comment by sminot** [comment]
Specifically, this is the link I'm thinking of - https://cran.r-project.org/web/packages/breakaway/breakaway.pdf

**Comment by sminot** [comment]
Something like this (https://stackoverflow.com/questions/39814916/how-can-i-see-output-of-rmd-in-github) might make the vignettes more viewable, perhaps

**Comment by adw96** [comment]
Thanks, Sam, and sorry for not responding earlier! 

Typically documentation for functions in R packages is contained in the `man` pages. If the package is installed and loaded, you can see the documentation for a specific function `myfun` by typing `?myfun`. 

The link you provided is a CRAN-compiled pdf of the manual pages. However, for various reasons we are no longer maintaining breakaway on CRAN, so that document is quite out of date. 

I've updated the document and there is a link to it on the main README. This change is currently only on the `testing` branch, but as soon as all Travis checks pass I will merge to master and close this issue, unless you have other concerns 😸

**Comment by adw96** [comment]
Check out [the manual](https://github.com/adw96/breakaway/blob/master/breakaway-manual.pdf), now linked from the homepage's README.
