### ISSUE TITLE
Clarification regarding blups in betta()

### ISSUE THREAD

**Issue by nmshahir** [adw96/breakaway#60]
Quick question regarding betta() output, would it be correct to assume that betta$blups would be considered the "corrected" richness estimations?

i.e. 
```
devtools::install_github("adw96/breakaway")
library(breakaway)
library(phyloseq)
data("GlobalPatterns")
ba <- breakaway(GlobalPatterns)
ss <- summary(ba) 
x_m <- model.matrix( ss$sestimate ~ ss$x_1 + Sample_Type)
bt <- betta(ss$estimate, ss$error, x_m)
```

bt$blups ==> richness estimates for GlobalPatterns corrected for Sample_Type and x_1
?

**Comment by adw96** [comment]
The `$blups` output of betta is the best unbiased prediction (BLUP) of the total species richness for each sample. Informally, it's a balance between the expected total species richness for each group and the observed species richness for each group. 

I'm not sure what you mean by "corrected". `ss$estimate` is the estimated total species richness, so it "corrects" the observed species richness in each sample for unobserved species. You could also talk about the *fitted* species richness from the `betta` model, which uses covariate information, so that gives you the expected true richness for each given covariate level. By default we don't output this (most folks are interested in using `betta` for hypothesis testing rather than estimation), but if you need it I could rewrite the interface to output it.
