### ISSUE TITLE
Calculating R2 or similar from a betta model output

### ISSUE THREAD

**Issue by cramjaco** [adw96/breakaway#69]
Hey breakaway team. I have less of an issue and more of a question. I can take this to another forum if you prefer. 
I was wondering if there is a suggested way of getting some standardized effect size, like an R^2 value from breakaway's `betta()` models. 

For instance if I modify `adw/stamps2018` 's example 
```

water2 <- GlobalPatterns %>%
  subset_samples(SampleType %in% c("Freshwater", 
                                   "Ocean")) %>%
  tax_glom("Order")


ba2 <- breakaway(water2)

bt2 <- betta(summary(ba2)$estimate,
            summary(ba2)$error,
            make_design_matrix(water2, "SampleType"))

bt2
```

```
> > bt2
> $table
>                 Estimates Standard Errors p-values
> (Intercept)     154.35507        3.720339        0
> predictorsOcean -17.73674        3.862773        0
> 
> $cov
>                 (Intercept) predictorsOcean
> (Intercept)        191.2065       -191.2065
> predictorsOcean   -191.2065        206.1275
> 
> $ssq_u
> [1] 14.74752
> 
> $homogeneity
> [1] 3.0396202 0.3855568
> 
> $global
> [1] 1375.497    0.000
> 
> $blups
> [1] 154.3395 154.3706 138.2215 134.5372 137.0963
```

I see that from the table that, among the "ocean" and "freshwater" samples, whether the predictor is "ocean" statistically associated with richness `bt2$table["predictorsOcean","p-values"]` = "0" and that ocean samples have lower richness than the freshwater samples `bt2$table["Estimates","p-values"]` = "-17.7 < 0.

I'd like some idea of how strong of a relationship this is. I can check the correlation coefficient by just correlating the sample type against some dummy variable indicating whether a sample is ocean or fresh water `cor(summary(ba2)$estimate, make_design_matrix(water2, "SampleType")[,2]) ^2` = 0.12, which suggests a relatively, but not ridiculously weak relationship between the two variables. That said, this approach seems to neglect the errors in the richness values, and maybe some other features as well. Is there some more breakaway appropriate way of measuring an R^2 value, a pseudo-R^2 value or something similar?

**Comment by cramjaco** [comment]
I read somewhere that R2 = cov(x,y)/(sd(x)*sd(y)), so I tried doing something similar with the covariance value from bt2$cov and the standard deviations of the richness and predictors data.

```
myCov <- bt2$cov["predictorsOcean", "predictorsOcean"]
mySdX <- sd(make_design_matrix(water2, "SampleType")[,2])
mySdY <- sd(summary(ba2)$estimate)

myCov/(mySdX*mySdY)
```
This me an answer of 31.1, which is clearly outside of the range of -1 to 1, which means I am misunderstanding something about how to calculate R^2 values or else what breakaway does.

**Comment by adw96** [comment]
Hi @cramjaco -- thanks for your interest in `breakaway` and `betta`. As you know, R^2 is the fraction of total variation explained by the model fit, and is commonly reported for a simple linear and multiple linear regression homoskedastic models. `betta` is a heteroskedastic regression model (because the different alpha diversity estimates have different uncertainties), and I've never seen an R^2 reported for such a model... but it seems to me to be a valid summary of the explanatory power of the model. I'm going to flag this is a feature request and implement it soon for you. 

Feel free to ping me if I don't follow up within the week :)

Amy

**Comment by cramjaco** [comment]
Awesome. Thanks!

**Comment by adw96** [comment]
Hi! This has now been implemented,  as `$r_squared_wls`. The R-squared that is introduced in introductory statistics classes is not completely appropriate for this model, since it is heteroskedastic, so I have implemented the heteroskedastic R-squared; see Eqn 7 of Willett & Singer, 1988, American Statistician.
  
Hope this helps! Example below:

```
> betta(c(1552, 1500, 884), c(305, 675, 205), cbind(1, c(0, 0, 1)))
$table
     Estimates Standard Errors p-values
[1,]      1526        294.0600     0.00
[2,]      -642        424.3689     0.13

$cov
          [,1]      [,2]
[1,]  166341.7 -166341.7
[2,] -166341.7  346430.7

$ssq_u
[1] 138064

$homogeneity
[1] 0.008750509 0.925471271

$global
[1] 1.833863e+01 1.849194e-05

$blups
[1] 1541.534 1519.954  884.000

$loglikelihood
[1] -21.63179

$aic
[1] 49.26357

$aicc
[1] 25.26357

$r_squared_wls
[1] 0.9951037
```
