### ISSUE TITLE
Model fit and specifying distributions for richness estimation

### ISSUE THREAD

**Issue by cjburgess** [adw96/breakaway#81]
Hi Amy,

I have been using breakaway for a while now; however, I came across an issue that many of my samples had richness estimates were not reasonable `reasonable = FALSE`. Examining the model fit it looked like they really weren't great fits. Looking deeper into my data I found that many of my models that did have good fits used the Kemp instead of the other distributions which I think would potentially be a better fit for some of my samples that used neg-binomial 

My Questions are:
1) If my models do not have reasonable fits is the estimate still usable/ better than just using observed richness?
2) Is there anyway to specify the underlying distribution you would like to use? 

~Chris

**Comment by adw96** [comment]
Hi Chris! Thanks for reaching out. 

1. Yes -- definitely much better (unless the model is doing something absolutely wild like the fitted observations are way off the trend -- I think I've caught almost all of these cases by now but please post an issue if you see this!). Using the observed richness doesn't account for bias or variance at all, so even a bad bias correction and a small variance (which can come out of an unreasonable model) is better than that!
2. By default breakaway will try to fit a Kemp model, and only if no Kemp models will fit will it go to a different model. You can specify a less well fitting model by just running, e.g., `chao_bunge(ps)` instead of `breakaway(ps)` where `ps` is a phyloseq object or similar, but breakaway does everything it can to make a Kemp model fit and there's no way to fix this as a user, unfortunately. 

I hope that answers your question but if not let me know!

Amy
