### ISSUE TITLE
could not find function "resample_estimate"

### ISSUE THREAD

**Issue by stan-iakhno** [adw96/breakaway#82]
Hi Amy,

Massive thanks for your efforts in developing the breakaway package (among others)! I am trying to go through the https://github.com/adw96/breakaway/blob/master/vignettes/diversity-hypothesis-testing.Rmd 

It seems that the function resample_estimate() is not there. At least concerning the version that I have (4.6.16). What could be a solution?

KR. Stan

**Comment by adw96** [comment]
Hi KR. Stan! 

I couldn't find any reference to `resample_estimate` at the link that you provided (which was to the [vignette](https://raw.githubusercontent.com/adw96/breakaway/master/vignettes/diversity-hypothesis-testing.Rmd)). This function has been deprecated because it's not a good way of looking at the variability in diversity estimates, and we have since developed a better one. We deprecated it when we developed the package [`DivNet`](https://github.com/adw96/DivNet). I recommend that tool instead. 

When you get a minute, could you please let me know how you found the reference to 
`resample_estimate`? I'd like updated it so folks don't find this outdated functionality in future.

Cheers, and thanks for checking out breakaway!

Amy

**Comment by stan-iakhno** [comment]
Hi Amy,

Thanks for your reply. I first tried to go through this https://github.com/adw96/breakaway/blob/master/vignettes/breakaway.Rmd tutorial. And this was the place where I found the depreciated function `resample_estimate.` Sorry, my original post had a wrong link. 

I am definitely using DivNet in my research.  It is a really cool thing! 

Take care!
Kind regards. Stan
