### ISSUE TITLE
Error message while trying to use function breakaway()

### ISSUE THREAD

**Issue by jehaab** [adw96/breakaway#92]
Hello,
I’m having problems using the breakaway function on my data.
I am analyzing 458 gut microbiome.
When I use the function sample_richness() on data counts at the family and species levels everything works fine, but I tried using the breakaway() function and it always stops at one sample and returns an error:
"Error in uniroot(poisson_fn, c(1e-04, 1e+06)) :
  f() values at end points not of opposite sign3"
And a warning for all other samples:
“48: In poisson_model(input_data, cutoff = cutoff) :
 Cut-off was too low: no data available for estimation”
I checked the model that was used by breakaway on my samples and it is always Poisson.
Also, there are no rare families/species in my samples, as the less common species are observed 35 times. Would that be a problem for the estimation?

**Comment by adw96** [comment]
Thanks, @jehaab ! I have fixed the issue on the testing branch, and will wait for breakaway to pass checks before I merge into master, at which point I will close this issue. 

In the meantime, since the sample richness is the best that you can do on this dataset, please use sample_richness *on this sample only* in the meantime 😸

**Comment by adw96** [comment]
Confirming that this issue is resolved in v4.7.2+ 😸
